### ISSUE TITLE
<Ctrl-C> of `nbd lo` does not destroy the NBD device

### ISSUE THREAD

**Issue by Merovius** [Merovius/nbd#13]
When connecting with `lo` and killing the process (via SIGINT or SIGTERM) it doesn't clean up the nbd-node, even though it could.

**Comment by prologic** [comment]
Should the device in `/dev` be removed?

**Comment by Merovius** [comment]
In general, no. The nbd driver has a fixed number of devices and pre-allocates the nodes in `/dev`. In general, they shouldn't be touched. When I say "destroy the device", I really mean "disconnect" - free up the used device number.

**Comment by prologic** [comment]
I see thanks for the explanation. I'll see if I can hack a PR for this.
