### ISSUE TITLE
Disconnect() fails with `netlink validate: mismatched sequence in netlink reply`

### ISSUE THREAD

**Issue by bduffany** [Merovius/nbd#18]
In my testing, calling `nbdnl.Disconnect()` seems to fail with "netlink validate: mismatched sequence in netlink reply"

The disconnect succeeds based on the kernel logs and also based on the fact that I can re-mount after disconnecting without any problems. It just seems like a validation error.

**Comment by Merovius** [comment]
Just wanted to say: Thank for all these issues, I'm seeing them and I hope to get around to a real response over the weekend.

**Comment by bduffany** [comment]
No problem, in the meantime I am also working on debugging on my end.

I tried running `nbd` with the env var `NLDEBUG=1` set (an option supported by the netlink Go lib) and it resulted in this output:

```
nl: send: {Header:{Length:28 Type:unknown(16) Flags:request Sequence:710513959 PID:848802} Data:[3 1 0 0 8 0 2 0 110 98 100 0]}
nl: recv: {Header:{Length:180 Type:unknown(16) Flags:0 Sequence:710513959 PID:848802} Data:[1 2 0 0 8 0 2 0 110 98 100 0 6 0 1 0 35 0 0 0 8 0 3 0 1 0 0 0 8 0 4 0 0 0 0 0 8 0 5 0 10 0 0 0 84 0 6 0 20 0 1 0 8 0 1 0 1 0 0 0 8 0 2 0 10 0 0 0 20 0 2 0 8 0 1 0 2 0 0 0 8 0 2 0 10 0 0 0 20 0 3 0 8 0 1 0 3 0 0 0 8 0 2 0 10 0 0 0 20 0 4 0 8 0 1 0 5 0 0 0 8 0 2 0 10 0 0 0 36 0 7 0 32 0 1 0 8 0 2 0 15 0 0 0 17 0 1 0 110 98 100 95 109 99 95 103 114 111 117 112 0 0 0 0]}
nl: send: {Header:{Length:92 Type:unknown(35) Flags:request|acknowledge Sequence:710513960 PID:848802} Data:[1 0 0 0 8 0 1 0 3 0 0 0 12 0 2 0 0 0 64 6 0 0 0 0 16 0 7 0 12 0 1 0 8 0 1 0 7 0 0 0 12 0 6 0 0 0 0 0 0 0 0 0 12 0 5 0 5 0 0 0 0 0 0 0 12 0 3 0 0 16 0 0 0 0 0 0]}
nl: recv: {Header:{Length:28 Type:unknown(35) Flags:0 Sequence:710513960 PID:848802} Data:[1 1 0 0 8 0 1 0 3 0 0 0]}
2023/06/01 21:33:37 Connected to /dev/nbd3
^C
2023/06/01 21:33:55 Disconnecting /dev/nbd3
nl: send: {Header:{Length:28 Type:unknown(35) Flags:request|acknowledge Sequence:710513961 PID:848802} Data:[2 0 0 0 8 0 1 0 3 0 0 0]}
nl: recv: {Header:{Length:36 Type:error Flags:0x100 Sequence:710513960 PID:848802} Data:[0 0 0 0 92 0 0 0 35 0 5 0 40 149 89 42 162 243 12 0]}
```

So it indeed looks like there's an unexpected sequence number in the mix. The pattern is

```
send 710513959
recv 710513959
send 710513960
recv 710513960
send 710513961
recv 710513960 <- mismatch
```

Interestingly, the mismatching sequence has `Type:error`.

I came across [this SO post](https://stackoverflow.com/questions/51370678/netlink-sequence-numbers-out-of-sequence ("MAC80211_HWSIM" family) suggesting to just retry the recv when this happens. So I patched the netlink library to do that, and the recv retry "works" in the sense that I get another message with the expected sequence number, just not sure if it's the "right" message. The data is identical, except one byte in the Data payload is different (not sure why, yet).

```
nl: send: {Header:{Length:28 Type:unknown(35) Flags:request|acknowledge Sequence:1810060145 PID:888624} Data:[2 0 0 0 8 0 1 0 3 0 0 0]}
nl: recv: {Header:{Length:36 Type:error Flags:0x100 Sequence:1810060144 PID:888624} Data:[0 0 0 0 92 0 0 0 35 0 5 0 112 83 227 107 48 143 13 0]}
nl: sequence number mismatch; retrying recv
nl: recv: {Header:{Length:36 Type:error Flags:0x100 Sequence:1810060145 PID:888624} Data:[0 0 0 0 28 0 0 0 35 0 5 0 113 83 227 107 48 143 13 0]}
```

Based on https://github.com/mdlayher/netlink/issues/108 it seems like a possible workaround is to manually call Send/Receive instead of Execute, and do this recv retry manually. But I will do a bit more digging first to try and understand why this is happening in the first place.
